# Generated by Django 5.2.15 on 2026-07-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditoria",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Auditoría",
                "verbose_name_plural": "Auditorías",
            },
        ),
        migrations.AddField(
            model_name="auditoria",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
    ]
