# Generated by Django 5.2.15 on 2026-07-02 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_cuenta", models.CharField(max_length=10, unique=True)),
                (
                    "tipo_cuenta",
                    models.CharField(
                        choices=[("AH", "Ahorros"), ("CC", "Cuenta Corriente")],
                        max_length=2,
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("fecha_apertura", models.DateField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("A", "Activa"), ("I", "Inactiva")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas",
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
    ]
