# Generated by Django 5.2.15 on 2026-07-02 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cuentas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("D", "Deposito"),
                            ("R", "Retiro"),
                            ("T", "Transferencia"),
                        ],
                        max_length=1,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "saldo_anterior",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("saldo_actual", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cuentas.cuenta"
                    ),
                ),
            ],
        ),
    ]
