# Generated by Django 5.2.16 on 2026-07-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
